### PR TITLE
Substituição parcial do projeto por AOP

### PR DESCRIPTION
**Pull request by miguelarauj1o**
@PedroClericuzi e @horaciojcfilho, abaixo segue a lista das classes no projeto. Cada uma tem um conjunto de modificações que eu acho viável em AOP. Idealmente, precisamos identificar todos os pontos passíveis de substituição. 

**Eu sugiro que trabalhemos neste Pull Request.
Cada alteração, marquem a classe que foi modificada.
Caso algum de vocês encontrem mais situações, basta me avisar que eu atualizo aqui.
Isso servirá também como material de apresentação para o professor.**

- [x] `healthwatcher.business.complaint.ComplaintRecord`
```` java 
this.validate(complaint);
````
- [x] `healthwatcher.business.complaint.DiseaseRecord`
Nada identificado.
- [x] `healthwatcher.business.employee.EmployeeRecord`
``` java 
public void insert(Employee employee);
```
- [x] `healthwatcher.business.healthguide.HealthUnitRecord`
Nada identificado.
- [x] `healthwatcher.business.healthguide.MedicalSpecialityRecord` 
Nada identificado.
- [x] `healthwatcher.business.HealthWatcherFacade`
```` java
public class HealthWatcherFacade extends java.rmi.server.UnicastRemoteObject implements IFacade {}
// [...]
private static HealthWatcherFacade singleton;
// [...]
public static void main(String[] args);
// [...]
private HealthWatcherFacade();
// [...]
this.fCid = new HealthWatcherFacadeInit();
// [...]
this.fCid.updateComplaint(q);
// [...]
public Complaint searchComplaint(int code);
// [...]
public DiseaseType searchDiseaseType(int code);
// [...]
static IPersistenceMechanism pmInit();
// [...]
````
- [x] `healthwatcher.business.HealthWatcherFacadeInit`
```` java
public void updateHealthUnit(HealthUnit unit);
// [...]
public void updateComplaint(Complaint complaint);
// [...]
public IteratorDsk searchSpecialitiesByHealthUnit(int code);
// [...]
public Complaint searchComplaint(int code);
// [...]
public DiseaseType searchDiseaseType(int code);
// [...]
public IteratorDsk searchHealthUnitsBySpeciality(int code);
// [...]
public IteratorDsk getSpecialityList();
// [...]
public IteratorDsk getDiseaseTypeList();
// [...]
public IteratorDsk getHealthUnitList();
// [...]
public IteratorDsk getPartialHealthUnitList();
// [...]
public void insert(Employee employee);
// [...]
public int insertComplaint(Complaint complaint);
// [...]
public Employee searchEmployee(String login);
// [...]
public IteratorDsk getComplaintList();
// [...]
public void update(Employee employee)
````
- [ ] `healthwatcher.data.mem.ComplaintRepositoryArray`
```` java
public class ComplaintRepositoryArray implements IComplaintRepository {}
````
- [x] `healthwatcher.data.mem.SymptomRepositoryArray`
```` java
public class SymptomRepositoryArray implements ISymptomRepository {}
// [...]
public void insert(Symptom symptom);
// [...]
public Symptom search(int code);
// [...]
public void remove(int code);
````
- [x] `healthwatcher.data.mem.SpecialityRepositoryArray`
```` java
public class SpecialityRepositoryArray implements ISpecialityRepository {}
// [...]
public SpecialityRepositoryArray();
// [...]
public void update(MedicalSpeciality specialty);
// [...]
public IteratorDsk getSpecialityList();
// [...]
public void insert(MedicalSpeciality specialty);
// [...]
public MedicalSpeciality search(int code);
// [...]
public void remove(int code);
````
- [x] `healthwatcher.data.mem.HealthUnitRepositoryArray`
```` java
public class HealthUnitRepositoryArray implements IHealthUnitRepository {}
// [...]
public void update(HealthUnit unit);
// [...]
public IteratorDsk getHealthUnitList();
// [...]
public IteratorDsk getPartialHealthUnitList();
// [...]
public void insert(HealthUnit unit);
// [...]
public HealthUnit search(int code);
// [...]
public void remove(int code);
````
- [x] `healthwatcher.data.mem.EmployeeRepositoryArray`
```` java
public class EmployeeRepositoryArray implements IEmployeeRepository {}
// [...]
public void insert(Employee employee);
// [...]
public void update(Employee employee);
// [...]
public Employee search(String login);
// [...]
public void remove(String login);
````
- [x] `healthwatcher.data.mem.DiseaseTypeRepositoryArray`
```` java
public class DiseaseTypeRepositoryArray implements IDiseaseRepository {}
// [...]
public DiseaseTypeRepositoryArray();
// [...]
public void update(DiseaseType tp);
// [...]
public void insert(DiseaseType tp);
// [...]
public DiseaseType search(int code);
// [...]
public void remove(int code);
````
- [ ] `healthwatcher.data.rdb.AddressRepositoryRDB`
```` java
public class AddressRepositoryRDB implements IAddressRepository {}
// [...]
public int insert(Address end);
// [...]
public Address search(int code);
````
- [x] `healthwatcher.data.rdb.SpecialityRepositoryRDB`
```` java
public class SpecialityRepositoryRDB implements ISpecialityRepository {}
// [...]
public IteratorDsk getSpecialityList();
// [...]
public void insert(MedicalSpeciality spec);
// [...]
public MedicalSpeciality search(int code);
````
- [x] `healthwatcher.data.rdb.HealthUnitRepositoryRDB`
```` java
public class HealthUnitRepositoryRDB implements IHealthUnitRepository {}
// [...]
public void update(HealthUnit us);
// [...]
public IteratorDsk getHealthUnitList();
// [...]
public IteratorDsk getPartialHealthUnitList();
// [...]
public IteratorDsk getHealthUnitListBySpeciality(int code);
// [...]
public void insert(HealthUnit hu);
// [...]
public HealthUnit search(int code);
// [...]
public HealthUnit partialSearch(int codigo);
````
- [x] `healthwatcher.data.rdb.EmployeeRepositoryRDB`
```` java
public class EmployeeRepositoryRDB implements IEmployeeRepository {}
// [...]
public void insert(Employee employee);
// [...]
public Employee search(String login);
// [...]
public boolean exists(String login);
// [...]
public void update(Employee employee);
````
- [x] `healthwatcher.data.rdb.DiseaseTypeRepositoryRDB`
```` java
public class DiseaseTypeRepositoryRDB implements IDiseaseRepository {}
// [...]
public IteratorDsk getDiseaseTypeList();
// [...]
public DiseaseType partialSearch(int codigo);
// [...]
public DiseaseType search(int code);
````
- [x] `healthwatcher.data.rdb.ComplaintRepositoryRDB`
```` java
public class ComplaintRepositoryRDB implements IComplaintRepository {}
// [...]
private FoodComplaint accessFood(int code);
// [...]
private AnimalComplaint accessAnimal(int codigo);
// [...]
private void accessComplaint(ResultSet resultSet, Complaint complaint);
// [...]
private SpecialComplaint accessSpecial(int code);
// [...]
public void update(Complaint complaint);
// [...]
private void deepInsertFood(FoodComplaint complaint);
// [...]
private void deepInsertAnimal(AnimalComplaint complaint);
// [...]
private void deepInsertCommon(Complaint complaint);
// [...]
public boolean exists(int code);
// [...]
public int insert(Complaint complaint);
// [...]
private void insertFood(FoodComplaint complaint);
// [...]
private void insertAnimal(AnimalComplaint complaint);
// [...]
private void insertSpecial(SpecialComplaint complaint);
// [...]
public Complaint search(int code);
// [...]
private void updateTimestamp(String value, String tableName, String id);
// [...]
private long searchTimestamp(String tableName, String id);
// [...]
public IteratorDsk getComplaintList();
````
- [x] `healthwatcher.data.ISymptomRepository`
Nada identificado.
- [x] `healthwatcher.data.ISpecialityRepository`
Nada identificado.
- [x] `healthwatcher.data.IHealthUnitRepository`
Nada identificado.
- [x] `healthwatcher.data.IEmployeeRepository`
Nada identificado.
- [x] `healthwatcher.data.IDiseaseRepository`
Nada identificado.
- [x] `healthwatcher.data.IComplaintRepository`
Nada identificado.
- [x] `healthwatcher.data.IAddressRepository`
Nada identificado.
- [x] `healthwatcher.model.address.Address`
```` java
public class Address implements java.io.Serializable {}
````
- [x] `healthwatcher.model.complaint.Symptom`
```` java
public class Symptom implements java.io.Serializable {}
````
- [x] `healthwatcher.model.complaint.SpecialComplaint`
```` java
public class SpecialComplaint extends Complaint {}
````
- [x] `healthwatcher.model.complaint.Situation` {}
```` java
public class Situation implements Serializable {}
````
- [x] `healthwatcher.model.complaint.DiseaseType`
```` java
public class DiseaseType implements Serializable {}
````
- [x] `healthwatcher.model.complaint.Complaint`
```` java
public abstract class Complaint implements Serializable {}
````
- [x] `healthwatcher.model.complaint.AnimalComplaint`
```` java
public class AnimalComplaint extends Complaint {}
````
- [x] `healthwatcher.model.employee.Employee`
```` java
public class Employee implements Serializable {}
````
- [x] `healthwatcher.model.healthguide.HealthUnit`
```` java
public class HealthUnit implements Serializable {}
````
- [x] `healthwatcher.model.healthguide.MedicalSpeciality`
```` java
public class MedicalSpeciality implements Serializable {}
````
- [ ] `healthwatcher.view.servlets.ServletSearchComplaintData`
```` java
public class ServletSearchComplaintData extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletSearchDiseaseData`
```` java
public class ServletSearchDiseaseData extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletSearchHealthUnitsBySpecialty`
```` java
public class ServletSearchHealthUnitsBySpecialty extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletWebServer`
```` java
public class ServletWebServer extends HWServlet {}
````
- [ ] `healthwatcher.view.servlets.ServletUpdateHealthUnitSearch`
```` java
public class ServletUpdateHealthUnitSearch extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletUpdateHealthUnitData`
```` java
public class ServletUpdateHealthUnitData extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletUpdateEmployeeSearch`
```` java
public class ServletUpdateEmployeeSearch extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletUpdateEmployeeData`
```` java
public class ServletUpdateEmployeeData extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletUpdateComplaintSearch`
```` java
public class ServletUpdateComplaintSearch extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletUpdateComplaintData`
```` java
public class ServletUpdateComplaintData extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletSearchSpecialtiesByHealthUnit`
```` java
public class ServletSearchSpecialtiesByHealthUnit extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletLogin`
```` java
public class ServletLogin extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletInsertFoodComplaint`
```` java
public class ServletInsertFoodComplaint extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletInsertEmployee`
```` java
public class ServletInsertEmployee extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletInsertAnimalComplaint`
```` java
public class ServletInsertAnimalComplaint extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletGetDataForSearchBySpeciality`
```` java
public class ServletGetDataForSearchBySpeciality extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletGetDataForSearchByHealthUnit`
```` java
public class ServletGetDataForSearchByHealthUnit extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletGetDataForSearchByDiseaseType`
```` java
public class ServletGetDataForSearchByDiseaseType extends HWServlet {}
// [...]
public void doGet(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.ServletConfigRMI`
```` java
public class ServletConfigRMI extends HWServlet {}
// [...]
public void doPost(HttpServletRequest request, HttpServletResponse response);
````
- [ ] `healthwatcher.view.servlets.HWServlet`
```` java
public abstract class HWServlet extends HttpServlet {}
// [...]
public void init(ServletConfig config);
````
- [ ] `healthwatcher.view.IFacade`
```` java
public interface IFacade extends Remote {}
````
- [x] `healthwatcher.Constants`
Nada identificado.
- [x] `lib.concurrency.ConcurrencyManager`
```` java
public synchronized void beginExecution(Object key);
// [...]
public synchronized void endExecution(Object key);
// [...]
````
- [x] `lib.distribution.rmi.IteratorRMITargetAdapter`
```` java
public class IteratorRMITargetAdapter extends UnicastRemoteObject implements IIteratorRMITargetAdapter {}
````
- [x] `lib.distribution.rmi.IteratorRMISourceAdapter`
```` java
public class IteratorRMISourceAdapter implements IteratorDsk, Serializable {}
// [...]
public void connect();
````
- [x] `lib.distribution.rmi.IIteratorRMITargetAdapter`
Nada identificado.
- [x] `lib.exceptions.UpdateEntryException`
```` java
public class UpdateEntryException extends Exception {}
````
- [x] `lib.exceptions.TransactionException`
```` java
public class TransactionException extends Exception {}
````
- [x] `lib.exceptions.SituationFacadeException`
```` java
public class SituationFacadeException extends Exception {}
````
- [x] `lib.exceptions.RepositoryException`
```` java
public class RepositoryException extends Exception {}
````
- [x] `lib.exceptions.PersistenceSoftException`
```` java
public class PersistenceSoftException extends RuntimeException {}
````
- [x] `lib.exceptions.PersistenceMechanismException`
```` java
public class PersistenceMechanismException extends Exception {}
````
- [x] `lib.exceptions.ObjectNotValidException`
```` java
public class ObjectNotValidException extends Exception {}
````
- [x] `lib.exceptions.ObjectNotFoundException`
```` java
public class ObjectNotFoundException extends Exception
````
- [x] `lib.exceptions.ObjectAlreadyInsertedException`
```` java
public class ObjectAlreadyInsertedException extends Exception {}
````
- [x] `lib.exceptions.InvalidSessionException`
```` java
public class InvalidSessionException extends Exception {}
````
- [x] `lib.exceptions.InvalidDateException`
```` java
public class InvalidDateException extends Exception {}
````
- [x] `lib.exceptions.InsertEntryException`
```` java
public class InsertEntryException extends Exception {}
````
- [x] `lib.exceptions.ExceptionMessages`
Nada identificado.
- [ ] `lib.exceptions.CommunicationException`
```` java
public class CommunicationException extends Exception implements Serializable {}
````
- [x] `lib.persistence.PersistenceMechanismMem`
```` java
public class PersistenceMechanismMem implements IPersistenceMechanism {}
// [...]
private static PersistenceMechanismMem singleton;
````
- [ ] `lib.persistence.PersistenceMechanism`
```` java
public class PersistenceMechanism implements IPersistenceMechanism {}
// [...]
private static PersistenceMechanism singleton;
// [...]
private PersistenceMechanism(String url, String user, String password, String driverClass);
// [...]
public synchronized PreparedStatement getPreparedStatement(String sql);
// [...]
public synchronized void rollbackTransaction();
// [...]
public synchronized void connect();
// [...]
public synchronized void commitTransaction();
// [...]
public synchronized void disconnect();
// [...]
public synchronized Object getCommunicationChannel();
// [...]
private synchronized Connection getCommunicationChannel(boolean porTransacao);
// [...]
public synchronized void beginTransaction();
// [...]
private synchronized void releaseCommunicationChannel(boolean porTransacao);
````
- [x] `lib.persistence.IPersistenceMechanism`
Nada identificado.
- [x] `lib.util.Schedule`
```` java
public Schedule(String segundoStr, String minutoStr, String horaStr);
// [...]
public static String format(Schedule horario, int formato);
// [...]
public static Schedule stringToHorario(String horarioStr, int formato);
// [...]
private void validaHorario(int segundo, int minuto, int hora);
````
- [x] `lib.util.LocalIterator`
```` java
public interface LocalIterator extends IteratorDsk {}
````
- [x] `lib.util.Library`
```` java
private static String readFile(String file);
````
- [x] `lib.util.IteratorDsk`
Nada identificado.
- [x] `lib.util.HTMLCode`
Nada identificado.
- [x] `lib.util.Functions`
Nada identificado.
- [x] `lib.util.Date`
```` java
public class Date implements Serializable {}
// [...]
public Date(int segundo, int minuto, int hora, int dia, int mes, int ano);
// [...]
public Date(String diaStr, String mesStr, String anoStr);
// [...]
public Date(String segundoStr, String minutoStr, String horaStr, String diaStr, String mesStr, String anoStr);
// [...]
public Date anteriorData();
// [...]
public boolean ehFinalDeSemana();
// [...]
public static String format(Date data, int formato);
// [...]
public static Date stringToData(String dataStr, int formato);
// [...]
public static void main(String args[]);
````
- [x] `lib.util.ConcreteIterator`
```` java
public class ConcreteIterator implements LocalIterator, Serializable {}
````

### CODE REVIEW

**Comment by miguelarauj1o** [comment]
De antemão, eu não acho que devemos modificar os casos `extends` e `implements`.
É possível usar AOP nestes casos, mas não é um caso que se encaixa idealmente.
OO é suficientemente correto.

**Comment by ghost** [comment]
@miguelarauj1o Vi muitos casos de `implements` Serializable para classes de modelo, seria legal adicionar esse `implements` através de um aspecto, porque isso só indica a forma de serialização do modelo e que é sujeito a mudanças. Além disso Serializable não adiciona qualquer método.

**Comment by ghost** [comment]
@miguelarauj1o Esse daqui já tá pronto. Aí é só tirar o ```implements``` das classes de modelo.

```(SerializableMarker.aj)```
```java
package aspects;

import java.io.Serializable;

public aspect SerializableMarker {
	declare parents: healthwatcher.model..* implements Serializable;
}
```

**Comment by ghost** [comment]
@miguelarauj1o O menino @PedroClericuzi tem um aspecto para controle de concorrência, resolvendo a bronca de healthwatcher.business.employee.EmployeeRecord. Como esse daqui foi ruim para testar acabamos ocultando os packages originais das classes aí precisa devolver isso.

```(EmployeeRecord.java)```
```java
package figures;

public class EmployeeRecord {
	private IEmployeeRepository employeeRepository;

	public EmployeeRecord(IEmployeeRepository rep) {
		this.employeeRepository = rep;
	}

	public Employee search(String login) throws ObjectNotFoundException, RepositoryException {
		return employeeRepository.search(login);
	}

	public void insert(Employee employee) throws ObjectNotValidException, ObjectAlreadyInsertedException, ObjectNotValidException, RepositoryException {
		employeeRepository.insert(employee);
	}

	public void update(Employee employee) throws ObjectNotValidException, ObjectNotFoundException, ObjectNotValidException, RepositoryException {
		employeeRepository.update(employee);
	}
}
```

```(ConcurrentRecorder.aj)```
```java
package aspects;

import figures.*;

public privileged aspect ConcurrentRecorder {
	private final ConcurrencyManager manager = new ConcurrencyManager();
	
	void around(Employee employee, EmployeeRecord record) throws ObjectAlreadyInsertedException, RepositoryException: call(public void EmployeeRecord.insert(Employee)) && args(employee) && target(record) {
		manager.beginExecution(employee.getLogin());
		
		if (record.employeeRepository.exists(employee.getLogin())) {
			throw new ObjectAlreadyInsertedException(ExceptionMessages.EXC_JA_EXISTE);
		}
		
		proceed(employee, record);
		
		manager.endExecution(employee.getLogin());
	}
}
```

**Comment by ghost** [comment]
@miguelarauj1o Mais outro aspecto para desacoplar a validação que estava em ```ComplaintRecord.java```:

```(ComplaintRecord.java)```
```java
package business.complaint;

import data.IComplaintRepository;
import figures.ObjectAlreadyInsertedException;
import figures.ObjectNotFoundException;
import figures.ObjectNotValidException;
import figures.RepositoryException;
import model.complaint.Complaint;
import util.IteratorDsk;

public class ComplaintRecord {
	private IComplaintRepository complaintRep;

	public ComplaintRecord(IComplaintRepository rep) {
		this.complaintRep = rep;
	}

	public Complaint search(int code) throws RepositoryException, ObjectNotFoundException {
		return complaintRep.search(code);
	}

	public int insert(Complaint complaint) throws ObjectNotValidException, ObjectAlreadyInsertedException, ObjectNotValidException, RepositoryException {
		if (complaintRep.exists(complaint.getCodigo())) {
			throw new ObjectAlreadyInsertedException("Complaint code already registered");
		}
		
		return complaintRep.insert(complaint);
	}

	public void update(Complaint q) throws RepositoryException, ObjectNotFoundException, ObjectNotValidException {
		complaintRep.update(q);
	}

	public IteratorDsk getComplaintList() throws RepositoryException, ObjectNotFoundException {
		return complaintRep.getComplaintList();
	}
}
```

```(ComplaintValidator.aj)```
```java
package aspects;

import business.complaint.ComplaintRecord;
import model.complaint.AnimalComplaint;
import model.complaint.Complaint;
import model.complaint.FoodComplaint;
import util.Functions;

public aspect ComplaintValidator {
	before(Complaint complaint): execution(public int ComplaintRecord.insert(Complaint)) && args(complaint) {
		validate(complaint);
	}
	
	private void validate(Complaint complaint) {
		Functions f = new Functions();

		if (complaint == null) {
			throw new IllegalArgumentException();
		}

		f.campoPreenchido(complaint.getDescricao());

		if (complaint instanceof AnimalComplaint) {
			f.campoPreenchido(((AnimalComplaint) complaint).getOccurenceLocalAddress());
			f.campoPreenchido(((AnimalComplaint) complaint).getAnimal());
		}

		if (complaint instanceof FoodComplaint) {
			f.campoPreenchido(((FoodComplaint) complaint).getQtdeComensais());
			f.campoPreenchido(((FoodComplaint) complaint).getQtdeDoentes());
		}
	}
}
```

**Pull request merged**
